"""500 inspirational quotes about fatherhood, fitness, discipline, and
strength — used by the content calendar to produce varied captions.

Mix of original DadStrong quotes and real attributed quotes from notable
fathers, athletes, and leaders.
"""

DAD_STRENGTH_QUOTES: list[str] = [
    # --- Fatherhood & Purpose (1-100) ---
    "A father's strength isn't measured in plates. It's measured in presence.",
    "The best thing a dad can do for his kids is take care of himself.",
    "Strong fathers raise strong families.",
    "My kids don't need a perfect dad. They need a present one.",
    "Fatherhood is the ultimate reason to never quit.",
    "I train so I can keep up with my kids for the next 50 years.",
    "Being a dad doesn't make you soft. It makes you unstoppable.",
    "Every rep is a promise to my family.",
    "Fathers who show up for themselves show up better for everyone else.",
    "My children are my greatest motivation and my deepest why.",
    '"The most important thing a father can do for his children is to love their mother." — Theodore Hesburgh',
    "The gym taught me patience. Fatherhood taught me purpose.",
    '"When you become a father, it changes you. It makes you want to be a better man." — Dwayne Johnson',
    "Your kids are watching. Make every action worth imitating.",
    "The weight on the bar is nothing compared to the weight of responsibility.",
    "Dad strength is real. It comes from love.",
    '"My father gave me the greatest gift anyone could give another person — he believed in me." — Jim Valvano',
    "A fit father is a gift to his family.",
    "The best inheritance you can leave your children is a healthy example.",
    "I lift for the ones who call me Dad.",
    '"Being a great father is like shaving. No matter how good you shaved today, you have to do it again tomorrow." — Reed Markham',
    "A dad who takes care of his body takes care of his family.",
    "Raise the bar — in the gym and at home.",
    "My kids don't need a hero. They need a dad who never gives up.",
    '"Of all the titles I have been privileged to have, Dad has always been the best." — Ken Norton',
    "The strongest thing a father can do is stay consistent.",
    "Dad life is hard. That's why we train.",
    '"I believe that what we become depends on what our fathers teach us at odd moments." — Umberto Eco',
    "A father's discipline is a family's foundation.",
    "No trophy compares to hearing your kid say they're proud of you.",
    "The gym is where I build the man my family deserves.",
    '"When my father didn\'t have my hand, he had my back." — Linda Poindexter',
    "My kids will inherit my habits before my wealth.",
    "The best version of me is the one my family gets at home.",
    "I didn't start training for me. I started for them.",
    '"It\'s not flesh and blood but the heart which makes us fathers and sons." — Friedrich Schiller',
    "A disciplined dad is a dependable dad.",
    '"My father used to say that it\'s never too late to do anything you wanted to do." — Michael Jordan',
    "I train because being healthy for my family is non-negotiable.",
    "The greatest gift I give my kids is showing them what consistency looks like.",
    '"Becoming a father, I think, inevitably changes your perspective on life." — LeBron James',
    "My family is my gym. Every day is a workout.",
    "Fathers set the standard. Make yours worth following.",
    '"I want my kids to see me and say \'That\'s my dad. He works hard.\'" — Mark Wahlberg',
    "The best pre-workout is remembering why you started.",
    "I don't just want to be there for my kids. I want to be strong for them.",
    '"Any man can be a father, but it takes someone special to be a Dad." — Anne Geddes',
    "Train hard. Be present. Love fiercely.",
    "Your family doesn't need you tired and broken. They need you strong.",
    "The hardest workout is getting up when nobody's watching. Do it anyway.",
    # --- Discipline & Consistency (51-150) ---
    '"Discipline equals freedom." — Jocko Willink',
    "Consistency isn't sexy. But the results are.",
    "Show up. Even when you don't feel like it. Especially then.",
    '"We are what we repeatedly do. Excellence, then, is not an act, but a habit." — Aristotle',
    "Motivation gets you started. Discipline keeps you going.",
    "Results are rented. You pay with discipline every single day.",
    '"The only discipline that lasts is self-discipline." — Bum Phillips',
    "You don't have to be extreme. You just have to be consistent.",
    '"Success isn\'t always about greatness. It\'s about consistency." — Dwayne Johnson',
    "The secret to success? Do the boring stuff consistently.",
    "Champions are made in the hours nobody sees.",
    '"Discipline is doing what needs to be done, even if you don\'t want to do it." — Jocko Willink',
    "One workout won't change your body. One hundred will change your life.",
    "The compound effect of daily discipline is unstoppable.",
    '"With self-discipline, most anything is possible." — Theodore Roosevelt',
    "Consistency turns average into exceptional.",
    "Discipline weighs ounces. Regret weighs tons.",
    '"Long-term consistency trumps short-term intensity." — Bruce Lee',
    "Stop waiting for motivation. Start building discipline.",
    "You are what you repeatedly do. Make it count.",
    '"Don\'t be afraid of failure. Be afraid of not trying." — Jocko Willink',
    "Discipline is remembering what you want.",
    "Fall in love with the process, not the outcome.",
    '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward." — Rocky Balboa',
    "Every day is a choice. Choose discipline.",
    "The only bad workout is the one you didn't do.",
    "Progress is not always visible. Keep going anyway.",
    '"The pain you feel today will be the strength you feel tomorrow." — Arnold Schwarzenegger',
    "Be so consistent that people think you're obsessed.",
    "Stack the days. Stack the reps. Stack the wins.",
    '"Discipline is the soul of an army." — George Washington',
    "Consistency is the silent killer of mediocrity.",
    '"Success is the sum of small efforts, repeated day in and day out." — Robert Collier',
    "Success is just a thousand small disciplines stacked together.",
    "Routine is not the enemy of freedom. It's the foundation.",
    '"The difference between a successful person and others is not a lack of strength but rather a lack in will." — Vince Lombardi',
    "Discipline is the root of all good qualities.",
    "Be patient with results. Be impatient with effort.",
    '"Repetition is the mother of learning, the father of action, which makes it the architect of accomplishment." — Zig Ziglar',
    "Do what is hard and your life will become easy.",
    '"Discipline is the bridge between goals and accomplishment." — Jim Rohn',
    "The gap between where you are and where you want to be is called consistency.",
    "Repeat. Repeat. Repeat. That's the formula.",
    '"Without self-discipline, success is impossible." — Lou Holtz',
    "You don't need a new plan. You need new discipline.",
    "Stop looking for hacks. Start building habits.",
    '"You will never always be motivated. You have to learn to be disciplined." — Jocko Willink',
    "The grind is not glamorous. But the payoff is priceless.",
    "Be the person who shows up no matter what.",
    '"Small daily improvements over time lead to stunning results." — Robin Sharma',
    "Success loves discipline and hates excuses.",
    # --- Mental Toughness & Mindset (101-200) ---
    '"You can\'t hurt me." — David Goggins',
    "Mental toughness is not born. It is built.",
    '"Suffering is a test. That\'s all it is. How you handle it is up to you." — David Goggins',
    "You are stronger than your strongest excuse.",
    '"The only limit to our realization of tomorrow will be our doubts of today." — Franklin D. Roosevelt',
    '"Be the hero of your own story." — Joe Rogan',
    "Comfort is the enemy of growth.",
    "Embrace the struggle. It's shaping who you're becoming.",
    '"I hated every minute of training, but I said, don\'t quit. Suffer now and live the rest of your life as a champion." — Muhammad Ali',
    "You don't grow when things are easy. You grow when things are hard.",
    '"Doubt kills more dreams than failure ever will." — Suzy Kassem',
    "Your greatest competition is who you were yesterday.",
    '"The successful warrior is the average man, with laser-like focus." — Bruce Lee',
    "Pressure makes diamonds. It also makes dads stronger.",
    '"It is not the critic who counts. The credit belongs to the man who is actually in the arena." — Theodore Roosevelt',
    "The mind is the most powerful muscle. Train it daily.",
    "Tough times don't last. Tough dads do.",
    '"A man is not finished when he is defeated. He is finished when he quits." — Richard Nixon',
    "Growth lives on the other side of discomfort.",
    "You didn't come this far to only come this far.",
    '"We don\'t rise to the level of our expectations. We fall to the level of our training." — Archilochus',
    "Strength doesn't come from winning. It comes from the struggle.",
    '"The mind is everything. What you think you become." — Buddha',
    "The comeback is always stronger than the setback.",
    '"Strength does not come from physical capacity. It comes from an indomitable will." — Mahatma Gandhi',
    "If it doesn't challenge you, it doesn't change you.",
    '"Adversity introduces a man to himself." — Albert Einstein',
    '"In any given moment we have two options: to step forward into growth or step back into safety." — Abraham Maslow',
    '"When you think you\'re done, you\'re only at 40 percent of your potential." — David Goggins',
    "Every setback is a setup for a comeback.",
    "The obstacle is the way. Go through it.",
    '"He who has a why to live can bear almost any how." — Friedrich Nietzsche',
    "What you tolerate is what you get. Raise your standards.",
    '"The impediment to action advances action. What stands in the way becomes the way." — Marcus Aurelius',
    "Resilience is the quiet muscle that matters most.",
    '"Do not pray for an easy life. Pray for the strength to endure a difficult one." — Bruce Lee',
    "The strongest steel is forged in the hottest fire.",
    "You are one decision away from a completely different life.",
    '"Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside." — Lance Armstrong',
    "Stay hungry. Stay humble. Stay hard.",
    '"You miss 100 percent of the shots you don\'t take." — Wayne Gretzky',
    "Courage is not the absence of fear. It's action in spite of it.",
    '"The body achieves what the mind believes." — Napoleon Hill',
    "Greatness is not given. It is earned every single day.",
    '"I\'m not the strongest. I\'m not the fastest. But I\'m the one that\'s not going to stop." — Rich Froning',
    "You were built for this. Trust yourself.",
    '"Rest at the end, not in the middle." — Kobe Bryant',
    "The world makes room for those who know where they're going.",
    # --- No Excuses & Accountability (201-300) ---
    "Excuses don't burn calories.",
    '"Don\'t count the days. Make the days count." — Muhammad Ali',
    "If it's important to you, you'll find a way. If not, you'll find an excuse.",
    '"Excuses are the tools of the incompetent." — Mike Tomlin',
    '"The best time to plant a tree was 20 years ago. The second best time is now." — Chinese Proverb',
    "You don't need more time. You need more focus.",
    '"I wake up at 3:30AM every morning because that\'s when no one else is working." — Mark Wahlberg',
    "Excuses make today easy and tomorrow hard.",
    '"Hold yourself responsible for a higher standard than anybody else expects of you." — Henry Ward Beecher',
    "You either make progress or you make excuses. Never both.",
    '"No one is coming to rescue you. It\'s all up to you." — Jocko Willink',
    '"If you really want to do something, you\'ll find a way. If you don\'t, you\'ll find an excuse." — Jim Rohn',
    "Accountability is the glue that ties commitment to results.",
    "You are responsible for your own happiness and your own health.",
    '"The only person you are destined to become is the person you decide to be." — Ralph Waldo Emerson',
    "Action cures fear. Excuses feed it.",
    "The only thing standing between you and your goals is the story you keep telling yourself.",
    '"Be the change you wish to see in the world." — Mahatma Gandhi',
    "You'll never be ready. Start anyway.",
    "Results happen when excuses don't.",
    '"Take ownership of your life. Don\'t make excuses." — Jocko Willink',
    "The man in the mirror is the only one who can change your life.",
    "Discipline is just accountability you give yourself.",
    '"Do or do not. There is no try." — Yoda',
    "You're not too busy. You're just not committed enough.",
    "Complaining burns zero calories.",
    '"It\'s supposed to be hard. If it were easy, everyone would do it." — Tom Hanks',
    "Your future self is begging you to try.",
    "Stop waiting for perfect conditions. They don't exist.",
    '"Don\'t let yesterday take up too much of today." — Will Rogers',
    "Accountability turns dreams into daily actions.",
    "You can have results or excuses. Not both.",
    '"If you want something you\'ve never had, you must be willing to do something you\'ve never done." — Thomas Jefferson',
    "The price of excellence is discipline. The cost of mediocrity is disappointment.",
    "Today's effort is tomorrow's reward.",
    '"The clock is ticking. Are you becoming the person you want to be?" — Greg Plitt',
    "Regret is more painful than discipline. Choose wisely.",
    "Be the kind of person who does what they say they'll do.",
    '"Don\'t let what you cannot do interfere with what you can do." — John Wooden',
    "Prove them wrong. Then prove yourself right.",
    '"Take care of your body. It\'s the only place you have to live." — Jim Rohn',
    "Don't talk about it. Be about it.",
    "Actions speak louder than intentions.",
    '"Winners embrace hard work. They love the discipline of it." — Mike Ditka',
    "There's no traffic on the extra mile.",
    '"I never lose. I either win or learn." — Nelson Mandela',
    "The longer you wait, the harder it gets.",
    '"You owe it to yourself to be the best you can possibly be." — Pete Rose',
    '"Success is the sum of small efforts, repeated day in and day out." — Robert Collier',
    "Champions adjust. Quitters complain.",
    '"You owe it to yourself to become everything you\'ve ever dreamed of being." — Chris Bumstead',
    # --- Strength & Training (301-400) ---
    "Stronger every day. That's the only goal that matters.",
    '"The iron never lies to you. Two hundred pounds is always two hundred pounds." — Henry Rollins',
    '"Everybody wants to be a bodybuilder, but nobody wants to lift no heavy weights." — Ronnie Coleman',
    "Train like your life depends on it. Because it does.",
    "The gym is therapy with better results.",
    "Sore today. Strong tomorrow.",
    '"The last three or four reps is what makes the muscle grow." — Arnold Schwarzenegger',
    "A one-hour workout is four percent of your day. No excuses.",
    "You don't find your limits by staying comfortable.",
    "Every rep brings you closer to the man you want to be.",
    '"Strength does not come from the physical capacity. It comes from an indomitable will." — Mahatma Gandhi',
    '"Your body can stand almost anything. It\'s your mind you have to convince." — David Goggins',
    '"The resistance that you fight physically in the gym transforms you." — Henry Rollins',
    "The only weight that matters is the one you carry with purpose.",
    "Strong is not a destination. It's a way of life.",
    '"For me, life is continuously being hungry. The meaning of life is not simply to exist." — Arnold Schwarzenegger',
    "Don't wish for a good body. Work for it.",
    "Build your body. Build your confidence. Build your legacy.",
    '"The gym is a sacred place. It\'s where you go to find yourself." — CT Fletcher',
    '"Iron sharpens iron." — Proverbs 27:17',
    "Your muscles don't know excuses. They only know work.",
    "Train for function. Train for family. Train for life.",
    '"It\'s still your motherf***ing set!" — CT Fletcher',
    "Strength isn't about how much you can lift. It's about how much you can endure.",
    '"Lift heavy or go home." — Ronnie Coleman',
    "The body is the servant of the mind. Train both.",
    "Every workout is a deposit in your health savings account.",
    '"The only way to define your limits is by going beyond them." — Arthur Clarke',
    "The grind doesn't stop because you're tired.",
    '"I do it as a therapy. I do it as something to keep me alive." — Arnold Schwarzenegger',
    '"Fitness is not about being better than someone else. It\'s about being better than you used to be." — Khloe Kardashian',
    '"There are no shortcuts. Everything is reps, reps, reps." — Arnold Schwarzenegger',
    "Your strongest muscle and your worst enemy is your mind.",
    "Sweat now. Shine later.",
    '"The gym floor is where champions are made." — Rich Froning',
    '"When you hit failure, your workout has just begun." — Ronnie Coleman',
    '"Pain is weakness leaving the body." — U.S. Marines',
    "Earned. Never given.",
    '"Training gives us an outlet for suppressed energies created by stress and thus tones the spirit just as exercise conditions the body." — Arnold Schwarzenegger',
    "The weight room is the great equalizer.",
    "Lift for the person you're becoming, not the person you were.",
    "Every set. Every rep. Every day. That's how you build a legacy.",
    '"I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times." — Bruce Lee',
    '"The best project you\'ll ever work on is you." — Sonny Franco',
    "Don't limit your challenges. Challenge your limits.",
    '"If something stands between you and your success, move it. Never be denied." — Dwayne Johnson',
    "The gym doesn't care about your title. Only your effort.",
    '"Yeah buddy! Light weight baby!" — Ronnie Coleman',
    "You're only one workout away from a better mood.",
    "The burn is just your body saying thank you.",
    # --- Leadership & Legacy (401-500) ---
    "Lead by example. There's no other way.",
    '"The legacy you leave is the life you lead." — Barack Obama',
    "Real leaders don't create followers. They create more leaders.",
    "Be the man your daughter wants to marry and your son wants to become.",
    '"A father\'s legacy is not what he leaves for his children but what he leaves in them." — Unknown',
    "Character is built when no one is watching.",
    '"Your children will follow your footsteps more than your advice." — Denzel Washington',
    '"Integrity is doing the right thing, even when no one is watching." — C.S. Lewis',
    "Leaders eat last and train first.",
    '"You are writing a story with your life. Make it worth reading." — Bob Goff',
    "The greatest leaders are the greatest servants.",
    '"What you do every day matters more than what you do once in a while." — Gretchen Rubin',
    "Build a life that inspires your kids to dream bigger.",
    '"A man\'s character is his fate." — Heraclitus',
    "Lead with humility. Train with intensity. Love with everything.",
    '"If you want to change the world, go home and love your family." — Mother Teresa',
    "Strong men create good times for their families.",
    "Be the calm in the storm for those around you.",
    '"A leader is one who knows the way, goes the way, and shows the way." — John C. Maxwell',
    '"Your kids don\'t need your money or your stuff. They need your time." — Denzel Washington',
    "Leave every room better than you found it.",
    '"The measure of a man is what he does with power." — Plato',
    "Great fathers don't just provide. They inspire.",
    '"You build a legacy by doing things that people can\'t stop talking about." — Dave Ramsey',
    '"At the end of the day, the most overwhelming key to a child\'s success is the positive involvement of parents." — Jane D. Hull',
    '"Be so good they can\'t ignore you." — Steve Martin',
    "Actions are the loudest form of leadership.",
    '"A good father is one of the most unsung, unpraised, unnoticed, and yet one of the most valuable assets in our society." — Billy Graham',
    "The way you treat yourself teaches others how to treat you.",
    '"The greatest mark of a father is how he treats his children when no one is looking." — Dan Pearce',
    "Earn respect through action, not words.",
    "Your vibe attracts your tribe. Make it a strong one.",
    '"True leadership is about making others better as a result of your presence." — Sheryl Sandberg',
    '"Live so that when your children think of fairness and integrity, they think of you." — H. Jackson Brown Jr.',
    "You can't pour from an empty cup. Fill yours first.",
    "The world needs more strong, present, loving fathers.",
    '"Every father should remember one day his son will follow his example, not his advice." — Charles Kettering',
    "Your family's health starts with yours.",
    "A fit dad is a fun dad.",
    '"The quality of a father can be seen in the goals, dreams, and aspirations he sets not only for himself but for his family." — Reed Markham',
    '"Legacy is not leaving something for people. It\'s leaving something in people." — Peter Strople',
    "Every generation gets stronger when fathers lead well.",
    '"I cannot think of any need in childhood as strong as the need for a father\'s protection." — Sigmund Freud',
    "A father's job is not to be perfect. It's to be present and persistent.",
    "Strength, honor, and love. That's the dad code.",
    '"The greatest wealth is health." — Virgil',
    "Be somebody nobody thought you could be.",
    '"It is easier to build strong children than to repair broken men." — Frederick Douglass',
    "Train your body. Feed your mind. Fuel your family.",
    "Real strength is being vulnerable enough to try again.",
    "Success without health is not success at all.",
    "Build yourself up so you can lift others higher.",
    "The best dads are built in the gym and proven at home.",
    '"Every sunrise brings a new opportunity. Don\'t waste it." — Dwayne Johnson',
    "Be relentless in the pursuit of what makes you better.",
    "A strong body houses a strong spirit.",
    "Protect your peace. Protect your health. Protect your family.",
    '"I\'m not telling you it\'s going to be easy. I\'m telling you it\'s going to be worth it." — Art Williams',
    "Champions are defined by what they do when nobody is cheering.",
    "Be the father you needed growing up.",
    '"The world breaks everyone, and afterward, many are strong at the broken places." — Ernest Hemingway',
    "Your greatest flex is being a good father.",
    "Rise. Grind. Repeat. For them.",
    "The iron and the family — both require your full commitment.",
    "Stay patient. Stay focused. Stay strong. Stay dad.",
    "Built different. Built for family.",
    '"The only easy day was yesterday." — U.S. Navy SEALs',
    "You are enough. But you can always become more.",
    "Legends aren't born. They're built — one rep at a time.",
    '"Health is the crown on the well man\'s head that only the sick can see." — Robin Sharma',
    "The strongest position is on your feet, leading your family forward.",
    "Invest in yourself. Your family earns the dividends.",
    '"The goal isn\'t to live forever. It\'s to create something that will." — Chuck Palahniuk',
    "Every father has the power to shape the future. Use it wisely.",
    "Strength is quiet. Confidence is silent. Hard work speaks.",
    "Don't count the cost. Count the reasons.",
    "Your health is a love letter to your future self.",
    "Train with purpose. Live with passion. Lead with love.",
    "Greatness is earned in the moments no one sees.",
    '"A father\'s love is the fuel that enables a normal human being to do the impossible." — Marion C. Garretty',
    "Show up. Work hard. Be kind. That's the whole plan.",
    '"The man who has confidence in himself gains the confidence of others." — Hasidic Proverb',
    "Strong today. Stronger tomorrow. Unstoppable forever.",
    "Dads who lift together, lead together.",
    '"The only failure is the failure to try." — Robin S. Sharma',
    "Build the body. Sharpen the mind. Strengthen the family.",
    "Your legacy isn't your deadlift PR. It's the lives you change.",
    "Keep going. Your future self will thank you.",
    '"Dads don\'t need to be told they\'re doing a good job. But it sure feels nice." — Justin Timberlake',
    "The best view comes after the hardest climb.",
    "Every day is leg day when you're carrying your family forward.",
    "You were made for this. Now go prove it.",
    # --- Bonus: More Fatherhood & Fitness (501-600) ---
    '"One man practicing sportsmanship is far better than a hundred teaching it." — Knute Rockne',
    "A strong back and a soft heart — that's the dad formula.",
    '"When you put yourself in the position to succeed, the only thing left is the work." — Dwayne Johnson',
    "The early alarm isn't punishment. It's investment.",
    '"My dad taught me that showing up is 80 percent of life." — Woody Allen',
    "Your body is the vehicle. Your family is the destination. Maintain both.",
    '"The most important thing in the world is family and love." — John Wooden',
    "Morning workouts hit different when you're training for something bigger than yourself.",
    '"Whatever you do, be different. Make yourself necessary." — Denzel Washington',
    "The best fathers aren't born. They're built through reps of patience and presence.",
    '"You can\'t put a limit on anything. The more you dream, the farther you get." — Michael Phelps',
    "A father's sweat equity pays dividends his kids will cash for a lifetime.",
    '"The only person who can tell you that you can\'t win is you." — Dwayne Johnson',
    "Tired is a feeling. Strong is a decision.",
    '"Good is not enough if better is possible." — Mark Wahlberg',
    "Your kids don't need a six-pack. They need a dad who doesn't give up.",
    '"Life is like riding a bicycle. To keep your balance, you must keep moving." — Albert Einstein',
    "Every plate loaded is a lesson in patience.",
    '"Once you learn to quit, it becomes a habit." — Vince Lombardi',
    "Fitness isn't selfish when it makes you a better dad.",
    '"Real integrity is doing the right thing, knowing that nobody\'s going to know whether you did it or not." — Oprah Winfrey',
    "Your sons are learning how to be men by watching you. Your daughters are learning what to expect from one.",
    '"The fight is won or lost far away from witnesses." — Muhammad Ali',
    "Dads who prioritize health prioritize their families.",
    '"It always seems impossible until it\'s done." — Nelson Mandela',
    "The barbell doesn't judge. It just asks if you're willing.",
    '"We generate fears while we sit. We overcome them by action." — Dr. Henry Link',
    "A healthy dad is a happy household.",
    '"Champions aren\'t made in gyms. Champions are made from something they have deep inside — a desire, a dream, a vision." — Muhammad Ali',
    "You don't have to be the strongest in the room. Just the most consistent.",
    '"If you\'re not making someone else\'s life better, then you\'re wasting your time." — Will Smith',
    "The deadlift doesn't care about your job title. Just your grip.",
    '"I never dreamed about success. I worked for it." — Estee Lauder',
    "When they ask your kids what their dad does, make sure the answer starts with 'He shows up.'",
    '"You don\'t have to be great to start, but you have to start to be great." — Zig Ziglar',
    "Every dad deserves to feel strong in his own body.",
    '"A champion is someone who gets up when they can\'t." — Jack Dempsey',
    "The gym is the classroom. Life is the exam.",
    '"Blood, sweat, and respect. The first two you give. The last one you earn." — Dwayne Johnson',
    "Strong hands build strong futures.",
    '"A real man cries. A real man has feelings. A real man can be vulnerable." — Terry Crews',
    "The weight doesn't get lighter. You just get stronger.",
    '"Fathers, be your daughter\'s first love and she\'ll never settle for anything less." — Unknown',
    "Rest days are part of the plan, not a break from it.",
    '"I\'m not where I want to be, but thank God I\'m not where I used to be." — Joyce Meyer',
    "Coach your kids. Coach yourself. Never stop learning.",
    '"Hard work beats talent when talent doesn\'t work hard." — Tim Notke',
    "Garage gym or commercial gym — the iron doesn't know the difference.",
    '"My heroes are the ones who survived doing it wrong, who made mistakes, but recovered from them." — Bono',
    "The snooze button is the enemy of every dad trying to level up.",
    '"What lies behind us and what lies before us are tiny matters compared to what lies within us." — Ralph Waldo Emerson',
    "Chest day, leg day, dad day — they all require showing up.",
    '"A father carries pictures where his money used to be." — Steve Martin',
    "The soreness fades. The pride of finishing doesn't.",
    '"The pain that you\'ve been feeling can\'t compare to the joy that\'s coming." — Romans 8:18',
    "Teach your kids to eat well by eating well yourself.",
    '"Be strong enough to stand alone, smart enough to know when you need help, and brave enough to ask for it." — Ziad K. Abdelnour',
    "A dad in the gym is a dad investing in decades more with his family.",
    '"Our greatest glory is not in never falling, but in rising every time we fall." — Confucius',
    "Your warm-up is someone else's max. Stay humble.",
    '"Being a father has been the most important role of my life." — Kobe Bryant',
    "The treadmill teaches patience. The squat rack teaches character.",
    '"No matter what accomplishments you make, somebody helped you." — Althea Gibson',
    "Health isn't a hobby for dads. It's a responsibility.",
    '"You have to expect things of yourself before you can do them." — Michael Jordan',
    "Every clean meal is a vote for the dad you want to be.",
    '"A father is someone who carries you on his shoulders when you\'re small and lifts your spirits when you\'re grown." — Unknown',
    "Protein shakes and bedtime stories — the dad life balance.",
    '"Excellence is not a singular act, but a habit." — Shaquille O\'Neal',
    "Your kids will remember the energy you brought home, not the money.",
    '"Success is not the key to happiness. Happiness is the key to success." — Albert Schweitzer',
    "Barbells and bedtimes — both require commitment.",
    '"The greatest thing a man can do for his children is love their mother." — Dwayne Johnson',
    "Train your weaknesses until they become your strengths.",
    '"Age is no barrier. It\'s a limitation you put on your mind." — Jackie Joyner-Kersee',
    "The reps you do when nobody's watching define who you are.",
    '"My father didn\'t tell me how to live. He lived and let me watch him do it." — Clarence Budington Kelland',
    "Every heavy set is a conversation with your future self.",
    '"To be the man, you gotta beat the man." — Ric Flair',
    "A dad who moves well, lives well, and loves well — that's the goal.",
    '"We suffer more often in imagination than in reality." — Seneca',
    "Your calendar shows what you value. Is the gym on it?",
    '"The only way to do great work is to love what you do." — Steve Jobs',
    "Chalk up. Show up. Lift up. That's the dad workout plan.",
    '"In the middle of difficulty lies opportunity." — Albert Einstein',
    "A strong grip on the bar. A soft touch with the kids. Both matter.",
    '"When I was young, I observed that nine out of ten things I did were failures. So I did ten times more work." — George Bernard Shaw',
    "Progress photos are great. But the real transformation is in how you show up at home.",
    '"It is not the mountain we conquer but ourselves." — Edmund Hillary',
    "Heavy squats and heavy responsibilities — built for both.",
    '"I have not failed. I\'ve just found 10,000 ways that won\'t work." — Thomas Edison',
    "The father who trains is the father who stays.",
    '"Tough times never last, but tough people do." — Robert Schuller',
    "Your one-rep max doesn't define you. Your daily effort does.",
    '"The harder the conflict, the more glorious the triumph." — Thomas Paine',
    "A healthy dad at 50 is worth more than a rich dad at 50 who can't play with his grandkids.",
    '"Winning isn\'t everything, but wanting to win is." — Vince Lombardi',
    "Lock in. Lift. Love. Repeat.",
    '"Nobody who ever gave his best regretted it." — George Halas',
    "Every burpee is a battle cry for the dad life.",
    '"My father was my teacher. But most importantly he was a great dad." — Beau Biden',
    "Two hundred pounds on the bar. Infinite love in the heart.",
    "The best gym partner is the voice in your head that says 'One more.'",
    '"First we form habits, then they form us." — Rob Gilbert',
    "Your kids will brag about your discipline long after they've forgotten your deadlift.",
    '"A truly rich man is one whose children run into his arms when his hands are empty." — Unknown',
    "Morning cardio hits harder when you know why you're running.",
    "The PR that matters most is being Present and Reliable.",
    '"Some people want it to happen, some wish it would happen, others make it happen." — Michael Jordan',
    "Failure is just another rep in disguise.",
    "Be the dad who says yes to the adventure because his body lets him.",
    '"The secret of getting ahead is getting started." — Mark Twain',
    "Every workout is proof that you chose yourself today.",
    "Strong enough to carry them. Brave enough to let them walk.",
    '"What we achieve inwardly will change outer reality." — Plutarch',
    "The gym is where excuses go to die and dads go to thrive.",
    "Fit dads don't have more time. They just have better priorities.",
    '"I can accept failure. Everyone fails at something. But I can\'t accept not trying." — Michael Jordan',
    "Your warmup today is your workout from a year ago. That's growth.",
    "They'll forget the toys you bought. They'll never forget the time you gave.",
    '"Stay committed to your decisions, but stay flexible in your approach." — Tony Robbins',
    "Every push-up is a push toward being a better man.",
    "The dad who recovers well performs well — in the gym and at home.",
    '"Don\'t watch the clock. Do what it does. Keep going." — Sam Levenson',
]
